### ISSUE TITLE
**ModuleNotFoundError: No module named 'tensorflow.contrib'** when 

### ISSUE THREAD

**Issue by dbdxnuliba** [google-research/tensor2robot#19]
I has successfully configure env as your install step instruction:

(google_RT1) tmirobot@tmirobot-System-Product-Name:~/ref$ python -m tensor2robot.research.pose_env.pose_env_test
pybullet build time: Dec 16 2022 10:07:09
Running tests under Python 3.8.15: /home/tmirobot/anaconda3/envs/google_RT1/bin/python3.8
[ RUN      ] PoseEnvTest.test_PoseEnv
[       OK ] PoseEnvTest.test_PoseEnv
----------------------------------------------------------------------
Ran 1 test in 0.065s

but when I 
**(google_RT1) robot@robot:~/ref$ python -m tensor2robot.research.pose_env.pose_env_models_test**
it shows the following infomation:**ModuleNotFoundError: No module named 'tensorflow.contrib'**

(google_RT1) robot@robot:~/ref$ python -m tensor2robot.research.pose_env.pose_env_models_test
2022-12-16 11:06:35.907244: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-16 11:06:35.980578: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/kinetic/share/euslisp/jskeus/eus//Linux64/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/usr/local/cuda/lib64
2022-12-16 11:06:35.980598: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-12-16 11:06:36.418803: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/kinetic/share/euslisp/jskeus/eus//Linux64/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/usr/local/cuda/lib64
2022-12-16 11:06:36.418856: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/kinetic/share/euslisp/jskeus/eus//Linux64/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/usr/local/cuda/lib64
2022-12-16 11:06:36.418865: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/robot/anaconda3/envs/google_RT1/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/robot/anaconda3/envs/google_RT1/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/robot/ref/tensor2robot/research/pose_env/pose_env_models_test.py", line 23, in <module>
    from tensor2robot.input_generators import default_input_generator
  File "/home/robot/ref/tensor2robot/input_generators/__init__.py", line 17, in <module>
    from tensor2robot.input_generators import abstract_input_generator
  File "/home/robot/ref/tensor2robot/input_generators/abstract_input_generator.py", line 25, in <module>
    from tensor2robot.models import abstract_model
  File "/home/robot/ref/tensor2robot/models/abstract_model.py", line 28, in <module>
    from tensor2robot.models import model_interface
  File "/home/robot/ref/tensor2robot/models/model_interface.py", line 33, in <module>
    from tensor2robot.preprocessors import abstract_preprocessor
  File "/home/robot/ref/tensor2robot/preprocessors/__init__.py", line 17, in <module>
    from tensor2robot.preprocessors import abstract_preprocessor
  File "/home/robot/ref/tensor2robot/preprocessors/abstract_preprocessor.py", line 22, in <module>
    from tensor2robot.utils import tensorspec_utils
  File "/home/robot/ref/tensor2robot/utils/tensorspec_utils.py", line 31, in <module>
    from tensorflow.contrib import framework as contrib_framework
**ModuleNotFoundError: No module named 'tensorflow.contrib'**

**Comment by AlexandrParkhomenko** [comment]
[tensor2robot ](https://github.com/google-research/tensor2robot) is **outdated**
https://github.com/tensorflow/tensorflow/issues/55620

```bash
pip install -r python-tensor2robot/requirements.txt
ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.0 
(from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 
2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 
2.12.0rc0, 2.12.0rc1, 2.12.0)
```

**Comment by AlexandrParkhomenko** [comment]
some migrations
https://www.tensorflow.org/api_docs/python/tf/TensorSpec
https://www.tensorflow.org/api_docs/python/tf/nest
https://www.tensorflow.org/api_docs/python/tf/tpu

**Comment by Andyyoung0507** [comment]
I also have this error when run 'python -m tensor2robot.research.pose_env.pose_env_models_test', did you solve it?

**Comment by yunaHwang** [comment]
Same, is there an alternative for using `from tensorflow.contrib import framework as contrib_framework`?

**Comment by LogSSim** [comment]
Did u solve this problem?
