### ISSUE TITLE
Error running `pose_env_models_test`

### ISSUE THREAD

**Issue by dtch1997** [google-research/tensor2robot#21]
In the last step of README, I ran:
```
python -m tensor2robot.research.pose_env.pose_env_models_test
```
However, all the tests failed with a similar error: 
```
NameError: name 'guzzler_use_compression' is not defined
```
Sample stack trace:
```
Traceback (most recent call last):
  File "/home/daniel/Documents/github/tensor2robot/research/pose_env/pose_env_models_test.py", line 75, in test_mc
    create_exporters_fn=None)
  File "/home/daniel/anaconda3/envs/robotics-transformer/lib/python3.7/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/daniel/anaconda3/envs/robotics-transformer/lib/python3.7/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/daniel/anaconda3/envs/robotics-transformer/lib/python3.7/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/daniel/Documents/github/tensor2robot/utils/train_eval.py", line 492, in train_eval_model
    mode=tf_estimator.ModeKeys.TRAIN,
  File "/home/daniel/Documents/github/tensor2robot/utils/train_eval.py", line 120, in provide_input_generator_with_model_information
    tf.logging.info('guzzler_use_compression %s', str(guzzler_use_compression))
NameError: name 'guzzler_use_compression' is not defined
  In call to configurable 'train_eval_model' (<function train_eval_model at 0x7f517c47e680>)
```

Library versions:
```
tensorflow==1.15.5
tensorflow-probability==0.7
tensorflow-agents==0.3
gin-config==0.5
```

**Comment by zhuoctian** [comment]
Hello! I got the same error.
Have u solved this Error?

**Comment by yunaHwang** [comment]
Hello, I also got the same error. Were you able to fix this?

**Comment by solisyke** [comment]
I guess it's some code bug. I comment the error line, and passed the test:)
